DROP TYPE IF EXISTS Grocery;
CREATE TYPE Grocery AS ENUM
(
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);


CREATE TABLE
IF NOT EXISTS shopping_list
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal
(10, 2),
    date_added TIMESTAMP DEFAULT now
() NOT NULL,
    checked Boolean
DEFAULT FALSE,
Category Grocery
);
